import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtemp, mkdir, readFile, rm, symlink, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { buildSourceRevision, readSourceRevision, recordSourceRevision } from "../../tools/civicresultmaps-mcp/source-revisions.ts";
import { createRuntimeContext, McpToolError } from "../../tools/civicresultmaps-mcp/runtime.ts";

const sha = (value) => createHash("sha256").update(value).digest("hex");
const source = (overrides = {}) => ({ id: "official", authority: "ZZ Elections", url: "https://elections.example.gov/export", localFile: "data/official.csv", sha256: sha("first bytes"), parser: "scripts/parse-zz.py", page: "12", sheet: "Results", cell: "A1", retrievedAt: "2026-09-08T00:00:00Z", reportingGrain: "county", ...overrides });
const artifact = (total = 10, sourceId = "official") => ({ state: { code: "ZZ" }, election: { year: 2024 }, native: { resultRows: [{ jurisdictionTag: "county:001", sourceId, totalVotes: total, votes: { A: total } }], reviewRows: [] } });
async function fixture({ sourceValue = source(), artifactValue = artifact() } = {}) { const root = await mkdtemp(path.join(os.tmpdir(), "crm-revisions-")); await Promise.all([mkdir(path.join(root, "etl", "state-configs"), { recursive: true }), mkdir(path.join(root, ".etl", "staging"), { recursive: true }), mkdir(path.join(root, "data"), { recursive: true }), mkdir(path.join(root, "scripts"), { recursive: true })]); await writeFile(path.join(root, "etl", "state-configs", "zz.json"), JSON.stringify({ code: "ZZ", electionYear: 2024, sources: [sourceValue], certifiedResults: { sourceId: "official" } })); await writeFile(path.join(root, ".etl", "staging", "zz-2024-staging.json"), JSON.stringify(artifactValue)); await writeFile(path.join(root, "data", "official.csv"), "first bytes"); await writeFile(path.join(root, "scripts", "parser.py"), "# parser v1\n"); return root; }
const ctx = (root) => createRuntimeContext({ repoRoot: root });
const record = (root) => recordSourceRevision(ctx(root), { state: "ZZ", sourceId: "official", confirmation: "RECORD_SOURCE_REVISION" });
async function rejects(work, code) { await assert.rejects(work, (error) => error instanceof McpToolError && (!code || error.code === code)); }

test("records config-selected bytes with declared lineage and reads the immutable revision", async () => { const root = await fixture(); try { const result = await record(root); assert.equal(result.status, "recorded"); assert.equal(result.revision.declaredDigestStatus, "verified"); assert.equal(result.revision.lineage.page, "12"); const loaded = await readSourceRevision(ctx(root), { state: "ZZ", sourceId: "official", revisionSha256: sha("first bytes") }); assert.equal(loaded.contentSha256, sha("first bytes")); assert.equal(loaded.lineage.cell, "A1"); assert.equal((await readFile(path.join(root, result.artifactPath))).toString(), "first bytes"); } finally { await rm(root, { recursive: true, force: true }); } });
test("same bytes are idempotent; changed bytes retain previous revision and observed diff", async () => { const root = await fixture(); try { const first = await record(root); const configPath = path.join(root, "etl", "state-configs", "zz.json"); const config = JSON.parse(await readFile(configPath)); config.sources[0].sha256 = sha("second bytes"); await writeFile(configPath, JSON.stringify(config)); await writeFile(path.join(root, "data", "official.csv"), "second bytes"); await writeFile(path.join(root, ".etl", "staging", "zz-2024-staging.json"), JSON.stringify(artifact(13, "replacement"))); const second = await record(root); assert.equal(second.status, "recorded"); assert.equal(second.revision.previousRevision, first.revision.contentSha256); assert.deepEqual(second.revision.diffFromPrevious.sourceIds, { added: ["replacement"], removed: ["official"] }); assert.equal(second.revision.diffFromPrevious.numericFields[0].field, "resultRows.totalVotes"); const repeat = await record(root); assert.equal(repeat.status, "already_recorded"); assert.equal(repeat.wrote, false); assert.equal((await readFile(path.join(root, first.artifactPath))).toString(), "first bytes"); } finally { await rm(root, { recursive: true, force: true }); } });
test("requires confirmation and rejects missing source, malformed source schema, and digest mismatch without guessing", async () => { const root = await fixture(); try { await rejects(() => recordSourceRevision(ctx(root), { state: "ZZ", sourceId: "official" }), "source_revision_confirmation_required"); await rejects(() => recordSourceRevision(ctx(root), { state: "ZZ", sourceId: "missing", confirmation: "RECORD_SOURCE_REVISION" }), "source_not_found"); const configPath = path.join(root, "etl", "state-configs", "zz.json"); const config = JSON.parse(await readFile(configPath)); config.sources[0].localFile = "data/a.csv;data/b.csv"; await writeFile(configPath, JSON.stringify(config)); await rejects(() => record(root), "retained_source_not_single_path"); config.sources[0] = source({ sha256: "not-a-digest" }); await writeFile(configPath, JSON.stringify(config)); const built = await buildSourceRevision(ctx(root), { state: "ZZ", sourceId: "official" }); assert.equal(built.revision.declaredDigestStatus, "invalid"); } finally { await rm(root, { recursive: true, force: true }); } });
test("fails closed for unsafe read and write junctions and invalid staging identity", async (t) => { const root = await fixture(); const outside = await mkdtemp(path.join(os.tmpdir(), "crm-revisions-outside-")); try { await rm(path.join(root, "data"), { recursive: true }); try { await symlink(outside, path.join(root, "data"), "junction"); } catch { t.skip("junction creation unavailable"); return; } await rejects(() => record(root), "unsafe_path"); await rm(path.join(root, "data"), { recursive: true }); await mkdir(path.join(root, "data")); await writeFile(path.join(root, "data", "official.csv"), "first bytes"); await rm(path.join(root, ".etl", "source-revisions"), { recursive: true, force: true }); await symlink(outside, path.join(root, ".etl", "source-revisions"), "junction"); await rejects(() => record(root), "unsafe_path"); await rm(path.join(root, ".etl", "source-revisions"), { recursive: true }); await writeFile(path.join(root, ".etl", "staging", "zz-2024-staging.json"), JSON.stringify({ state: { code: "YY" }, election: { year: 2024 }, native: {} })); await rejects(() => buildSourceRevision(ctx(root), { state: "ZZ", sourceId: "official" }), "invalid_staging_identity"); } finally { await rm(root, { recursive: true, force: true }); await rm(outside, { recursive: true, force: true }); } });
test("does not record a source that mutates during the record action", async () => { const root = await fixture(); try { const context = { ...ctx(root), beforeSourceRevisionPersistence: async () => writeFile(path.join(root, "data", "official.csv"), "second bytes") }; await rejects(() => recordSourceRevision(context, { state: "ZZ", sourceId: "official", confirmation: "RECORD_SOURCE_REVISION" }), "source_mutated_during_record"); const revisionPath = path.join(root, ".etl", "source-revisions", "zz", "official", sha("first bytes")); await assert.rejects(() => readFile(path.join(revisionPath, "source.bin"))); } finally { await rm(root, { recursive: true, force: true }); } });
test("rejects config/parser and staging changes after preview before immutable persistence", async () => { const root = await fixture(); try { const context = { ...ctx(root), beforeSourceRevisionPersistence: async () => { const configPath = path.join(root, "etl", "state-configs", "zz.json"); const config = JSON.parse(await readFile(configPath)); config.sources[0].parser = "scripts/changed.py"; await writeFile(configPath, JSON.stringify(config)); await writeFile(path.join(root, ".etl", "staging", "zz-2024-staging.json"), JSON.stringify(artifact(11))); } }; await rejects(() => recordSourceRevision(context, { state: "ZZ", sourceId: "official", confirmation: "RECORD_SOURCE_REVISION" }), "source_mutated_during_record"); } finally { await rm(root, { recursive: true, force: true }); } });
test("detects same-total canonical county substitution and only records safe lineage aliases", async () => { const root = await fixture({ sourceValue: source({ sheet: undefined, sheetName: "Alias sheet", row: "44", retrieval: { token: "secret", method: "download", url: "https://elections.example.gov/export?signature=secret" } }) }); try { const first = await record(root); const configPath = path.join(root, "etl", "state-configs", "zz.json"); const config = JSON.parse(await readFile(configPath)); config.sources[0].sha256 = sha("second bytes"); await writeFile(configPath, JSON.stringify(config)); await writeFile(path.join(root, "data", "official.csv"), "second bytes"); await writeFile(path.join(root, ".etl", "staging", "zz-2024-staging.json"), JSON.stringify({ ...artifact(10), native: { resultRows: [{ jurisdictionTag: "county:999", sourceId: "official", totalVotes: 10, votes: { A: 10 } }] } })); const second = await record(root); assert.deepEqual(second.revision.diffFromPrevious.numericFields, []); assert.match(second.revision.diffFromPrevious.canonicalRows.added[0], /county:999/); assert.match(second.revision.diffFromPrevious.canonicalRows.removed[0], /county:001/); assert.equal(first.revision.lineage.sheet, "Alias sheet"); assert.equal(first.revision.lineage.row, "44"); assert.equal(first.revision.observed.retrieval.token, undefined); assert.equal(first.revision.observed.retrieval.sourceUrl, "https://elections.example.gov/export"); } finally { await rm(root, { recursive: true, force: true }); } });
test("read rejects symlinked or mismatched immutable source bytes", async (t) => { const root = await fixture(); const outside = path.join(os.tmpdir(), `crm-revision-source-${Date.now()}`); try { const result = await record(root); await writeFile(outside, "first bytes"); await rm(path.join(root, result.artifactPath)); try { await symlink(outside, path.join(root, result.artifactPath), "file"); } catch { t.skip("symlink creation unavailable"); return; } await rejects(() => readSourceRevision(ctx(root), { state: "ZZ", sourceId: "official", revisionSha256: sha("first bytes") }), "unsafe_path"); } finally { await rm(root, { recursive: true, force: true }); await rm(outside, { force: true }); } });
test("idempotent record refuses deleted, tampered, or linked existing revision artifacts", async (t) => { const root = await fixture(); const outside = path.join(os.tmpdir(), `crm-revision-manifest-${Date.now()}`); try { const first = await record(root); await rm(path.join(root, first.artifactPath)); await rejects(() => record(root), "retained_source_unavailable"); await writeFile(path.join(root, first.artifactPath), "tampered"); await rejects(() => record(root), "immutable_artifact_mismatch"); await writeFile(path.join(root, first.artifactPath), "first bytes"); const manifest = path.join(root, first.manifestPath); await writeFile(outside, await readFile(manifest)); await rm(manifest); try { await symlink(outside, manifest, "file"); } catch { t.skip("symlink creation unavailable"); return; } await rejects(() => record(root), "unsafe_path"); } finally { await rm(root, { recursive: true, force: true }); await rm(outside, { force: true }); } });
test("duplicate canonical rows are retained as a multiset and changed with equal aggregates", async () => { const root = await fixture({ artifactValue: artifact({ resultRows: [{ jurisdictionTag: "county:001", sourceId: "official", localUnit: "A", contest: "President", candidate: "A", totalVotes: 3, votes: { A: 3 } }, { jurisdictionTag: "county:001", sourceId: "official", localUnit: "A", contest: "President", candidate: "A", totalVotes: 7, votes: { A: 7 } }] }) }); try { await record(root); const configPath = path.join(root, "etl", "state-configs", "zz.json"); const config = JSON.parse(await readFile(configPath)); config.sources[0].sha256 = sha("second bytes"); await writeFile(configPath, JSON.stringify(config)); await writeFile(path.join(root, "data", "official.csv"), "second bytes"); await writeFile(path.join(root, ".etl", "staging", "zz-2024-staging.json"), JSON.stringify(artifact({ resultRows: [{ jurisdictionTag: "county:001", sourceId: "official", localUnit: "A", contest: "President", candidate: "A", totalVotes: 4, votes: { A: 4 } }, { jurisdictionTag: "county:001", sourceId: "official", localUnit: "A", contest: "President", candidate: "A", totalVotes: 6, votes: { A: 6 } }] }))); const second = await record(root); assert.deepEqual(second.revision.diffFromPrevious.numericFields, []); assert.equal(second.revision.diffFromPrevious.canonicalRows.changed.length, 1); } finally { await rm(root, { recursive: true, force: true }); } });
test("same source bytes retain stored revision and flag changed observed parser implementation", async () => { const root = await fixture(); try { const first = await record(root); assert.equal(first.revision.parserIdentity.observedImplementation.status, "observed"); assert.match(first.revision.parserIdentity.observedImplementation.sha256, /^[a-f0-9]{64}$/); await writeFile(path.join(root, "scripts", "parser.py"), "# parser v2\n"); const repeat = await record(root); assert.equal(repeat.status, "already_recorded"); assert.equal(repeat.revision.recordedAt, first.revision.recordedAt); assert.equal(repeat.currentBindingStatus.stale.parserImplementation, true); } finally { await rm(root, { recursive: true, force: true }); } });
